# Default values for spring-petclinic-microservices

# Default values for spring-petclinic-microservices

global:
  namespace: default
  dockerRegistry: docker.io
  imageRepository: vuhoabinhthachhoa
  imagePullPolicy: Always
  imageTag: latest

# Standard environment variables without YAML anchors
configServerEnv:
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server:8888"
  - name: SPRING_CLOUD_CONFIG_URI
    value: "http://config-server:8888"
  - name: SPRING_CLOUD_CONFIG_FAIL_FAST
    value: "true"

# Discovery server specific environment
discoveryServerEnv:
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server:8888"
  - name: SPRING_CLOUD_CONFIG_URI
    value: "http://config-server:8888"
  - name: SPRING_CLOUD_CONFIG_FAIL_FAST
    value: "true"
  - name: SERVER_PORT
    value: "8761"

# Common environment for all services that depend on discovery
serviceEnv:
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server:8888"
  - name: SPRING_CLOUD_CONFIG_URI
    value: "http://config-server:8888"
  - name: SPRING_CLOUD_CONFIG_FAIL_FAST
    value: "true"
    
services:
  # 1. Config server must start first - no dependencies
  config-server:
    name: config-server
    image:
      repository: spring-petclinic-config-server
      tag: latest
    port: 8888
    replicas: 1
    
  # 2. Discovery server starts next - depends on config server
  discovery-server:
    name: discovery-server
    image:
      repository: spring-petclinic-discovery-server
      tag: latest
    port: 8761
    replicas: 1
    env:
      - *configServerEnv
      - name: SERVER_PORT
        value: "8761"
    
  # 3. Admin server - depends on config and discovery
  admin-server:
    name: admin-server
    image:
      repository: spring-petclinic-admin-server
      tag: latest
    port: 9090
    replicas: 1
    env:
      - *configServerEnv
    
  # 4. API Gateway - the entry point for external traffic
  api-gateway:
    name: api-gateway
    image:
      repository: spring-petclinic-api-gateway
      tag: latest
    port: 8080
    replicas: 1
    env:
      - *configServerEnv
    ingress:
      enabled: true
      host: petclinic.local
      path: /
      
  # Business services
  customers-service:
    name: customers-service
    image:
      repository: spring-petclinic-customers-service
      tag: latest
    port: 8080
    replicas: 1
    env:
      - *configServerEnv
    
  vets-service:
    name: vets-service
    image:
      repository: spring-petclinic-vets-service
      tag: latest
    port: 8080
    replicas: 1
    env:
      - *configServerEnv
    
  visits-service:
    name: visits-service
    image:
      repository: spring-petclinic-visits-service
      tag: latest
    port: 8080
    replicas: 1
    env:
      - *configServerEnv
    
  genai-service:
    name: genai-service
    image:
      repository: spring-petclinic-genai-service
      tag: latest
    port: 8080
    replicas: 1
    env:
      - *configServerEnv