# Values for spring-petclinic-microservices
# global:
#   namespace: default
#   dockerRegistry: docker.io
#   imageRepository: vuhoabinhthachhoa
#   imagePullPolicy: Always
#   imageTag: latest

global:
  namespace: default  # Will be overridden per environment (dev, staging, prod)
  dockerRegistry: docker.io
  imageRepository: vuhoabinhthachhoa
  imagePullPolicy: Always
  imageTag: latest
  baseDomain: petclinic.local  # Base domain for all environments

# Common environment configurations as anchor
common: &commonEnv
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server:8888"

services:
  # Config server configuration
  config-server:
    name: config-server
    image:
      repository: spring-petclinic-config-server
      tag: latest
    port: 8888
    replicas: 1
    env:
      - name: SERVER_PORT
        value: "8888"
    
  # Discovery server configuration
  discovery-server:
    name: discovery-server
    image:
      repository: spring-petclinic-discovery-server
      tag: latest
    port: 8761
    replicas: 1
    env:
      - name: SPRING_CONFIG_IMPORT
        value: "configserver:http://config-server:8888"
      - name: SERVER_PORT
        value: "8761"
    
  # API Gateway configuration
  api-gateway:
    name: api-gateway
    image:
      repository: spring-petclinic-api-gateway
      tag: latest
    port: 8080
    replicas: 1
    env: 
      - *commonEnv
      
  # Business services (explicit configuration without merges)
  customers-service:
    name: customers-service
    image:
      repository: spring-petclinic-customers-service
      tag: latest
    port: 8081
    replicas: 1
    env: 
      - *commonEnv
    
  vets-service:
    name: vets-service
    image:
      repository: spring-petclinic-vets-service
      tag: latest
    port: 8083
    replicas: 1
    env: 
      - *commonEnv
    
  visits-service:
    name: visits-service
    image:
      repository: spring-petclinic-visits-service
      tag: latest
    port: 8082
    replicas: 1
    env: 
      - *commonEnv
    
  genai-service:
    name: genai-service
    image:
      repository: spring-petclinic-genai-service
      tag: latest
    port: 8084
    replicas: 1
    env: 
      - *commonEnv

  # Admin server
  admin-server:
    name: admin-server
    image:
      repository: spring-petclinic-admin-server
      tag: latest
    port: 9090
    replicas: 1
    env: 
      - *commonEnv

  tracing-server:
    name: tracing-server
    owner: openzipkin
    image:
      repository: zipkin
      tag: latest
    port: 9411
    replicas: 1
    env:
      - *commonEnv
