# Values for spring-petclinic-microservices
global:
  namespace: default
  dockerRegistry: docker.io
  imageRepository: vuhoabinhthachhoa
  imagePullPolicy: Always
  imageTag: latest

# Config server environment - reads from git repo
configServerEnv:
  - name: SERVER_PORT
    value: "8888"

# Discovery server minimal bootstrap environment
discoveryServerEnv:
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server:8888"
  - name: SERVER_PORT
    value: "8761"

# Minimal environment for all other services
serviceEnv:
  - name: SPRING_CONFIG_IMPORT
    value: "configserver:http://config-server:8888"

services:
  # 1. Config server must start first - no dependencies
  config-server:
    name: config-server
    image:
      repository: spring-petclinic-config-server
      tag: latest
    port: 8888
    replicas: 1
    
  # 2. Discovery server starts next - depends on config server
  discovery-server:
    name: discovery-server
    image:
      repository: spring-petclinic-discovery-server
      tag: latest
    port: 8761
    replicas: 1
    
  # 3. Admin server - depends on config and discovery
  admin-server:
    name: admin-server
    image:
      repository: spring-petclinic-admin-server
      tag: latest
    port: 9090
    replicas: 1
    
  # 4. API Gateway - the entry point for external traffic
  api-gateway:
    name: api-gateway
    image:
      repository: spring-petclinic-api-gateway
      tag: latest
    port: 8080
    replicas: 1
    ingress:
      enabled: true
      host: petclinic.local
      path: /
      pathType: Prefix
      ingressClassName: nginx
      
  # Business services
  customers-service:
    name: customers-service
    image:
      repository: spring-petclinic-customers-service
      tag: latest
    port: 8080
    replicas: 1
    
  vets-service:
    name: vets-service
    image:
      repository: spring-petclinic-vets-service
      tag: latest
    port: 8080
    replicas: 1
    
  visits-service:
    name: visits-service
    image:
      repository: spring-petclinic-visits-service
      tag: latest
    port: 8080
    replicas: 1
    
  genai-service:
    name: genai-service
    image:
      repository: spring-petclinic-genai-service
      tag: latest
    port: 8080
    replicas: 1