global:
  namespace: dev-review
services:
  admin-server:
    image:
      tag: latest
    replicas: 1
  api-gateway:
    image:
      tag: 673b876
    replicas: 1
    ingress:
      host: petclinic-review.local
  config-server:
    image:
      tag: latest
    replicas: 1
  customers-service:
    image:
      tag: latest
    replicas: 1
  discovery-server:
    image:
      tag: latest
    replicas: 1
  genai-service:
    image:
      tag: latest
    replicas: 1
  vets-service:
    image:
      tag: latest
    replicas: 1
  visits-service:
    image:
      tag: 673b876
    replicas: 1
