{{- range $name, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      {{- if ne $service.name "config-server" }}
      # Wait for config server (except for config-server itself)
      initContainers:
      - name: wait-for-config
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup config-server; do echo waiting for config-server; sleep 2; done;']
      {{- end }}
      containers:
      - name: {{ $service.name }}
        image: {{ $.Values.global.dockerRegistry }}/{{ $.Values.global.imageRepository }}/{{ $service.image.repository }}:{{ $service.image.tag }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ $service.port }}
        env:
          # Static variable: always present
          - name: EUREKA_INSTANCE_HOSTNAME
            value: {{ $name }}

          # Only include the following if $service.env exists
          {{- if hasKey $service "env" }}
          {{- range $service.env }}
          - name: {{ .name }}
            {{- if hasKey . "value" }}
            value: {{ .value | quote }}
            {{- else if hasKey . "valueFrom" }}
            valueFrom:
              {{- toYaml .valueFrom | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
{{- end }}