{{- range $name, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      {{- if eq $service.name "config-server" }}
      # Config server doesn't wait for anything
      {{- else if eq $service.name "discovery-server" }}
      # Discovery server only waits for config-server
      initContainers:
      - name: wait-for-config
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup config-server; do echo waiting for config-server; sleep 2; done;']
      {{- else }}
      # All other services wait for both config-server and discovery-server
      initContainers:
      - name: wait-for-dependencies
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup config-server && nslookup discovery-server; do echo waiting for dependencies; sleep 2; done;']
      {{- end }}
      containers:
      - name: {{ $service.name }}
        image: {{ $.Values.global.dockerRegistry }}/{{ $.Values.global.imageRepository }}/{{ $service.image.repository }}:{{ $service.image.tag }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ $service.port }}
        {{- if eq $service.name "discovery-server" }}
        # Simple health probes for discovery-server
        readinessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 45
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: 8761
          initialDelaySeconds: 60
          periodSeconds: 30
        {{- end }}
        env:
          # Static variable: always present
          - name: EUREKA_INSTANCE_HOSTNAME
            value: {{ $service.name }}

          # Include environment variables based on the service type
          {{- if eq $service.name "discovery-server" }}
          {{- with $.Values.discoveryServerEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- else }}
          {{- with $.Values.serviceEnv }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
{{- end }}