{{- range $name, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      initContainers:
      {{- if ne $service.name "config-server" }}
      - name: wait-for-config-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z config-server 8888; do echo "Waiting for config-server..."; sleep 3; done;']
      {{- end }}
      {{- if ne $service.name "discovery-server" }}
      - name: wait-for-discovery-server
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z discovery-server 8761; do echo "Waiting for discovery-server..."; sleep 3; done;']
      {{- end }}
      containers:
      - name: {{ $service.name }}
        image: {{ $.Values.global.dockerRegistry }}/{{ $service.owner | default $.Values.global.imageRepository }}/{{ $service.image.repository }}:{{ $service.image.tag }}
        imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ $service.port }}
        env:
          - name: EUREKA_INSTANCE_HOSTNAME
            value: {{ $service.name | quote }}
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            value: "http://discovery-server:8761/eureka/"
          {{- if eq $service.name "config-server" }}
          - name: SPRING_CLOUD_CONFIG_SERVER_BOOTSTRAP
            value: "true"
          {{- else }}
          - name: SPRING_CONFIG_IMPORT
            value: "optional:configserver:http://config-server:8888"
          - name: SPRING_CLOUD_CONFIG_URI
            value: "http://config-server:8888"
          {{- end }}
          {{- if $service.env }}
          {{- range $service.env }}
          - name: {{ .name }}
            value: {{ .value | quote }}
          {{- end }}
          {{- end }}
        resources:
          requests:
            memory: "384Mi"
            cpu: "250m"
          limits:
            memory: "768Mi"
            cpu: "500m"
{{- end }}
