{{- range $name, $service := .Values.services }}
{{- if and (hasKey $service "ingress") $service.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $service.name }}-ingress
  namespace: {{ $.Values.global.namespace }}
spec:
  rules:
  - host: {{ $service.ingress.host }}
    http:
      paths:
      - path: {{ $service.ingress.path | default "/" }}
        pathType: Prefix
        backend:
          service:
            name: {{ $service.name }}
            port:
              number: {{ $service.port }}
{{- end }}
{{- end }}