{{- range $name, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
  
  labels:
    app: {{ $service.name }}
    monitoring: enabled
spec:
  selector:
    app: {{ $service.name }}
  ports:
  - name: http
    port: {{ $service.port }}
    targetPort: {{ $service.port }}
  type: {{ $service.serviceType | default "ClusterIP" }}
{{- end }}
